### ISSUE TITLE
To API εχει σταματησει να ανανεωνει τα δεδομενα απο 14-04-2022

### ISSUE THREAD

**Issue by kyriakid1s** [Covid-19-Response-Greece/covid19-greece-api#26]

**Comment by AlexDelitzas** [comment]
Unfortunately, Heroku has disabled Github integration, and thus automatic deploys, due to this [attack](https://github.blog/2022-04-15-security-alert-stolen-oauth-user-tokens/). When the problem has been resolved, the API will be working again. 

Meanwhile you can fetch data directly from the corresponding files : [https://github.com/Covid-19-Response-Greece/covid19-greece-api/tree/master/data/greece](https://github.com/Covid-19-Response-Greece/covid19-greece-api/tree/master/data/greece).
